### ISSUE TITLE
Unhandled exception error + wont detect WMP when run as administrator

### ISSUE THREAD

**Issue by Hrobo776** [T0biasCZe/Windows-Media-Player-Discord-RPC#5]
Whenever I run the exe file, it detects the WMP and the song/music its playing, however, it throws an unhandled exception error right after it loads up.
![image](https://github.com/T0biasCZe/Windows-Media-Player-Discord-RPC/assets/154055859/12dd5fb2-5974-404f-bdb9-682cb0e952a6)

I decided to run the exe as administrator hoping it would work, it loads just fine, however, it doesnt detect WMP and just says "Stopped". Console reads: "error trying to read WMP data, retrying", followed by another line saying "aborting", repeating every second
![image](https://github.com/T0biasCZe/Windows-Media-Player-Discord-RPC/assets/154055859/e69ff7e7-2892-4bc8-9f50-4ea37da1ba28)

**Comment by T0biasCZe** [comment]
What does it show in the details inside the unhandled exception error?

**Comment by T0biasCZe** [comment]
And it doesn't work when run as admin, since when running as admin it can't read the data from WMP that's running as user

**Comment by Hrobo776** [comment]
This is what it says exactly

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Discord_WMP.Form1.update_Tick(Object sender, EventArgs e) in C:\Users\tobik\Source\Repos\T0biasCZe\Windows-Media-Player-Discord-RPC\Discord WMP\Form1.cs:line 301
>    at System.Windows.Forms.Timer.OnTick(EventArgs e)
>    at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> Discord WMP
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///E:/DRP4WMP/Discord%20WMP.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9037.0 built by: NET481REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9037.0 built by: NET481REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9037.0 built by: NET481REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9037.0 built by: NET481REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ----------------------------------------
> Interop.WMPLib
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///E:/DRP4WMP/Interop.WMPLib.DLL
> ----------------------------------------
> CsvHelper
>     Assembly Version: 30.0.0.0
>     Win32 Version: 30.0.1.0
>     CodeBase: file:///E:/DRP4WMP/CsvHelper.DLL
> ----------------------------------------
> Microsoft.Bcl.AsyncInterfaces
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.700.19.46214
>     CodeBase: file:///E:/DRP4WMP/Microsoft.Bcl.AsyncInterfaces.DLL
> ----------------------------------------
> System.Numerics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.9037.0 built by: NET481REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> Microsoft.Bcl.HashCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.700.19.46214
>     CodeBase: file:///E:/DRP4WMP/Microsoft.Bcl.HashCode.DLL
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Assembly Version: 0.0.0.0
>     Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
> ----------------------------------------
> DiscordRPC
>     Assembly Version: 1.2.1.24
>     Win32 Version: 1.2.1.24
>     CodeBase: file:///E:/DRP4WMP/DiscordRPC.DLL
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
> 
> 
>

**Comment by Hrobo776** [comment]
I updated the program but it still wouldnt open, still throwing the same Unhandled exception error as seen in the first image

**Comment by T0biasCZe** [comment]
Could you copy the details from the exception dialog? So I could know on which line the error is thrown (since you updated the line got changed)

**Comment by T0biasCZe** [comment]
hmm do you have discord installed and running? since in the error it mentions line 301, on which the discord rich presence is being set. and it may throw error         
(if you do not want to use discord there is checkbox in settings to disable the discord functionality)

**Comment by keroblin** [comment]
Also having this error, runs fine with Discord and Windows Media Player closed, but then immediately throws errors when Discord is opened

**Comment by keroblin** [comment]
this is my error message

> See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord_WMP.Form1.update_Tick(Object sender, EventArgs e) in C:\Users\tobik\Source\Repos\T0biasCZe\Windows-Media-Player-Discord-RPC\Discord WMP\Form1.cs:line 307
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Discord WMP
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Programs/Discord%20WMP/Discord%20WMP.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Interop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Programs/Discord%20WMP/Interop.WMPLib.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
CsvHelper
    Assembly Version: 30.0.0.0
    Win32 Version: 30.0.1.0
    CodeBase: file:///D:/Programs/Discord%20WMP/CsvHelper.DLL
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 1.0.0.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///D:/Programs/Discord%20WMP/Microsoft.Bcl.AsyncInterfaces.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Microsoft.Bcl.HashCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///D:/Programs/Discord%20WMP/Microsoft.Bcl.HashCode.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
DiscordRPC
    Assembly Version: 1.2.1.24
    Win32 Version: 1.2.1.24
    CodeBase: file:///D:/Programs/Discord%20WMP/DiscordRPC.DLL
----------------------------------------
Windows.Media
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/SysNative/WinMetadata/Windows.Media.winmd
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Windows.Foundation
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/SysNative/WinMetadata/Windows.Foundation.winmd
----------------------------------------
System.Runtime.InteropServices.WindowsRuntime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.WindowsRuntime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.WindowsRuntime.dll
----------------------------------------
System.Runtime.WindowsRuntime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.WindowsRuntime/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.WindowsRuntime.dll
----------------------------------------
Windows.Storage
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/WINDOWS/SysNative/WinMetadata/Windows.Storage.winmd
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by T0biasCZe** [comment]
please try this build if it works or if it still throws error
**_[old file deleted]_**

**Comment by keroblin** [comment]
![image](https://github.com/T0biasCZe/Windows-Media-Player-Discord-RPC/assets/56348046/45fe0386-333a-4dee-81ad-52974d17f126)
unfortunately this now doesn't ask me about Discord at all and shows these windows. It does not sync with discord either, but there are no errors thrown

**Comment by T0biasCZe** [comment]
I apologize, I accidentally uploaded old zip, this is the file with the potential fix implemented:
[Discord WMP.zip](https://github.com/T0biasCZe/Windows-Media-Player-Discord-RPC/files/13985737/Discord.WMP.zip)

**Comment by keroblin** [comment]
Hi again and thanks for all your help,
Unfortunately, while not crashing and now displaying the data correctly in the window, it is not showing in Discord still at this stage. Is there anything more I need to do?

**Comment by keroblin** [comment]
Also when I click the taskbar tray icon to open the window and view the data, it will work for a couple of seconds before crashing and closing, unfortunately without an error report
![crash discord wmp](https://github.com/T0biasCZe/Windows-Media-Player-Discord-RPC/assets/56348046/7a2eb797-aa2b-4812-b015-19a708ca7df8)

**Comment by T0biasCZe** [comment]
try inserting "1076519967631093891" into the empty textbox at the top (without the quotes)

**Comment by keroblin** [comment]
Unfortunately this doesn't do anything
When I click the settings button the app still crashes after a few seconds and it doesn't link to my Discord

**Comment by keroblin** [comment]
![crash discord wmp 2](https://github.com/T0biasCZe/Windows-Media-Player-Discord-RPC/assets/56348046/2bee9fce-3fd1-41df-aaac-47484f3fbe09)

**Comment by T0biasCZe** [comment]
When you restart it does the ID you entered get saved or not (it should)
Because what worries me is that in the debug values, it shows "Initialized:
False", so the Discord RPC doesn't want to get started for some reason even
though it's enablrd

Dne po 22. 1. 2024 14:46 uživatel Casper ***@***.***> napsal:

**Comment by dethram** [comment]
I am having the issues where it won't remember the App ID, the version of this I am using is the one from this thread because the newest version is being treated as a virus and won't stay on my computer for more than a few seconds (even with threat protection turned off and my registry edited to turn off virus scan). The program is recognizing that WMP is open and playing audio but it will not connect to Discord with my Discord App ID in the fill in area.

![Image](https://github.com/user-attachments/assets/cd7eaebd-2654-4602-b42c-723c3d4df56c)

**Comment by dethram** [comment]
I am having the issues where it won't remember the App ID, the version of this I am using is the one from this thread because the newest version is being treated as a virus and won't stay on my computer for more than a few seconds (even with threat protection turned off and my registry edited to turn off virus scan). The program is recognizing that WMP is open and playing audio but it will not connect to Discord with my Discord App ID in the fill in area.

![Image](https://github.com/user-attachments/assets/bf846f98-2ffd-45c5-932e-9d11946e06bb)

**Comment by T0biasCZe** [comment]
what antivirus are you using? i know malwarebytes sometimes accidentally flags windows forms software as virus

**Comment by dethram** [comment]
I'm only using Windows Defender

**Comment by Hrobo776** [comment]
Hello sorry for not responding
Current new release works perfectly fine (albeit had to fiddle with the antivirus (turn it off temporarily then put it as exception), I use BitDefender which I know to be a bit sensitive)

**Comment by Hrobo776** [comment]
It still works although throws another Unhandled Exception error with this:

startIndex cannot be larger than length of string
Parameter name: startIndex.

**Comment by Hrobo776** [comment]
This exception error is only thrown on specific media files (with no pattern whatsoever, length of path doesnt actually have an effect of when this is shown)

**Comment by T0biasCZe** [comment]
> startIndex cannot be larger than length of string

hmm that seems to be issue with the SMTP media info sharing with Windows...
Would you be able to share one of the affected files that causes the error?
